language: node__js
node__js: 
    - "14"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
services:
  - docker

script:
  - docker build -t $DOCKER_USERNAME/node_auth:$TRAVIS_BUILD_NUMBER .
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $DOCKER_USERNAME/node_auth:$TRAVIS_BUILD_NUMBER

